version: 2
updates:
  - package-ecosystem: "swift"
    directories:
      - "/SwiftFirecracker"
      - "/agent"
      - "/cli"
      - "/clients/swift"
      - "/control-plane"
      - "/shared"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "swift"
    reviewers:
      - "samcat116"
    assignees:
      - "samcat116"
