version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "go"
    reviewers:
      - "samcat116"
    assignees:
      - "samcat116"
