import Foundation

// IAM phase 3 (issue #480), rebuilt for the unified role store (issue #604):
// the Cedar schema, generated from the role-definition rows and the code-side
// action registry.
//
// The registry (`IAMRoleRegistry`) stays the curated source of truth for the
// action *inventory*; the roles themselves are `iam_roles` rows (seeded
// defaults included), threaded in as `RoleDescriptor`s. Role permits carry
// explicit action lists, so the schema declares no role action-groups — only
// the per-service groups guardrail wildcards compile to.

/// Generates the Cedar schema: entity types, the per-operation action
/// inventory, per-service action groups (the compilation target for
/// `service:*` guardrail patterns), the per-role `Grants` fields, and the
/// fixed condition vocabulary as the request `Context`.
enum CedarSchemaBuilder {

    // MARK: - Action groups

    /// The action group holding every action of one service (`vm`, `volume`,
    /// …). This is what a `vm:*` guardrail pattern compiles to, so a service
    /// ceiling keeps covering actions shipped after it was written — the
    /// wildcard resolves at evaluation time, not when the guardrail was saved.
    static func serviceGroupName(_ service: String) -> String { "svc:\(service)" }

    /// One action declaration. `resourceTypes` is nil for pure groups (the
    /// service groups), which can never be the action of a request.
    struct ActionDecl: Equatable, Sendable {
        let name: String
        /// The groups this action (or group) is a *member of*.
        let memberOf: [String]
        let resourceTypes: [CedarEntityType]?
    }

    /// The full action inventory: service groups, then every registry action,
    /// sorted for a deterministic schema.
    static func actionDecls() -> [ActionDecl] {
        var decls: [ActionDecl] = []

        for service in IAMRoleRegistry.actionServices.sorted() {
            decls.append(ActionDecl(name: serviceGroupName(service), memberOf: [], resourceTypes: nil))
        }

        for action in IAMRoleRegistry.allActions.sorted() {
            var memberOf: [String] = []
            if let service = action.split(separator: ":", maxSplits: 1).first {
                memberOf.append(serviceGroupName(String(service)))
            }
            decls.append(ActionDecl(name: action, memberOf: memberOf, resourceTypes: resourceTypes(for: action)))
        }
        return decls
    }

    // MARK: - appliesTo

    /// The container chain every project-scoped resource sits beneath.
    private static let projectContainers: [CedarEntityType] = [.project, .folder, .organization]

    /// The resource types an action can be requested against.
    ///
    /// Deliberately coarse in v1: each service's actions apply to the
    /// service's own entity types plus the containers above them, because
    /// `create`/`list` checks target a container (the resource does not exist
    /// yet) while everything else targets the resource. The one sharpened case
    /// is `project:create`, which excludes `Project` — "Projects do not nest"
    /// is a tier-0 invariant worth encoding where the validator can see it.
    static func resourceTypes(for action: String) -> [CedarEntityType] {
        if action == "project:create" { return [.folder, .organization] }
        let service = action.split(separator: ":", maxSplits: 1).first.map(String.init) ?? ""
        switch service {
        case "vm": return [.vm] + projectContainers
        case "sandbox": return [.sandbox, .sandboxSnapshot] + projectContainers
        case "volume": return [.volume, .volumeSnapshot] + projectContainers
        case "image": return [.image] + projectContainers
        case "network": return [.network] + projectContainers
        case "floatingip": return [.floatingIP] + projectContainers
        case "serviceaccount": return [.serviceAccount] + projectContainers
        case "operation": return [.vm, .sandbox] + projectContainers
        case "project": return projectContainers
        case "folder": return [.folder, .organization]
        case "org": return [.organization]
        case "group": return [.organization]
        case "quota": return projectContainers
        case "site": return [.site, .folder, .organization]
        case "agent": return [.agent, .folder, .organization]
        case "iam": return CedarEntityType.nodeTypes
        default:
            // A new service nobody mapped yet: the broadest valid answer, so
            // its actions validate everywhere rather than nowhere.
            return CedarEntityType.nodeTypes
        }
    }

    // MARK: - Schema text

    /// The Cedar schema in the human-readable schema format, with one
    /// `Grants` field pair per role-definition row.
    static func schemaText(roles: [RoleDescriptor]) -> String {
        var lines: [String] = [
            "// Generated by CedarSchemaBuilder from IAMRoleRegistry and the",
            "// iam_roles rows (issues #480, #604). Regenerate rather than edit.",
            "",
        ]

        // The flattened per-request grants the entity-slice loader computes
        // from `role_bindings`: bindings stay data read per-request from
        // Postgres (docs/architecture/iam.md), so they arrive in the request
        // context rather than in the compiled policy set. Each principal type
        // gets its own set because Cedar sets are homogeneous. One field group
        // per role row, ordered by id: rebuilds on two replicas must produce
        // identical text for the same version.
        lines.append("type Grants = {")
        for role in roles.sorted(by: { $0.id.uuidString < $1.id.uuidString }) {
            lines.append("    \(CedarText.stringLiteral(role.grantsUsersField)): Set<User>,")
            lines.append("    \(CedarText.stringLiteral(role.grantsGroupsField)): Set<Group>,")
            lines.append("    \(CedarText.stringLiteral(role.grantsServiceAccountsField)): Set<ServiceAccount>,")
            lines.append("    \(CedarText.stringLiteral(role.grantsWorkloadsField)): Set<Workload>,")
        }
        lines.append("};")
        lines.append("")

        // The fixed condition vocabulary (`mfa`, `ip_range`) rides here;
        // `expires_at` is enforced when bindings are read and
        // `tags`/`environment` match the resource, so neither needs context.
        lines.append("type Context = {")
        lines.append("    \(CedarText.stringLiteral("grants")): Grants,")
        lines.append("    \(CedarText.stringLiteral("mfa"))?: Bool,")
        lines.append("    \(CedarText.stringLiteral("sourceIP"))?: ipaddr,")
        lines.append("};")
        lines.append("")

        lines.append("entity Group;")
        lines.append("entity User in [Group] {")
        lines.append("    \(CedarText.stringLiteral("memberOfOrgs")): Set<Organization>,")
        lines.append("    \(CedarText.stringLiteral("systemAdmin")): Bool,")
        lines.append("};")
        // A directly registered SPIFFE workload identity (issue #491).
        // Principal-only and deliberately attribute-free: a workload is not a
        // member of anything — no groups, no orgs — so every grant it has is
        // an explicit binding, and the membership-shaped platform policies
        // (`principal is User`-scoped) never apply to it. ServiceAccount is
        // declared with the node types below: it is a resource as well as a
        // principal.
        lines.append("entity Workload;")

        // `environment` is declared (optionally) on every node type, not just
        // the three that store one: an environment-conditioned guardrail
        // compiles to `resource has environment && …`, and the strict
        // validator rejects a `has` that can never be true. Container types
        // simply never carry the attribute at evaluation time.
        for entity in CedarEntityType.nodeTypes {
            let parents = parentTypes(for: entity)
            let head =
                parents.isEmpty
                ? "entity \(entity.rawValue)"
                : "entity \(entity.rawValue) in [\(parents.map(\.rawValue).joined(separator: ", "))]"
            var attrs = ["\(CedarText.stringLiteral("environment"))?: String"]
            if entity == .network {
                // A global network (no project) is readable by every
                // authenticated user — the tier-1 open-network policy keys on
                // this attribute.
                attrs.append("\(CedarText.stringLiteral("openToAllUsers")): Bool")
            }
            lines.append("\(head) {")
            for attr in attrs {
                lines.append("    \(attr),")
            }
            lines.append("};")
        }
        lines.append("")

        for decl in actionDecls() {
            var head = "action \(CedarText.stringLiteral(decl.name))"
            if !decl.memberOf.isEmpty {
                head += " in [\(decl.memberOf.map { CedarText.stringLiteral($0) }.joined(separator: ", "))]"
            }
            guard let resourceTypes = decl.resourceTypes else {
                lines.append("\(head);")
                continue
            }
            lines.append("\(head) appliesTo {")
            lines.append("    principal: [User, ServiceAccount, Workload],")
            lines.append("    resource: [\(resourceTypes.map(\.rawValue).joined(separator: ", "))],")
            lines.append("    context: Context,")
            lines.append("};")
        }

        return lines.joined(separator: "\n") + "\n"
    }

    /// Every entity type that can sit at or beneath `entity` in the tree —
    /// the transitive closure of `parentTypes` read downward.
    ///
    /// The write-time ceiling check (#484) uses this to bound its enumeration:
    /// a binding on a project can only ever reach the types that can live
    /// under a project, so the other request environments are not worth a
    /// solver process. Derived from the same declarations the schema emits, so
    /// a new resource type is covered the moment its parentage is declared.
    static func descendantTypes(of entity: CedarEntityType) -> [CedarEntityType] {
        CedarEntityType.nodeTypes.filter { candidate in
            var frontier: [CedarEntityType] = [candidate]
            var seen: Set<String> = [candidate.rawValue]
            while let next = frontier.popLast() {
                if next == entity { return true }
                for parent in parentTypes(for: next) where seen.insert(parent.rawValue).inserted {
                    frontier.append(parent)
                }
            }
            return false
        }
    }

    /// The legal Cedar parents of an entity type — the same one-parent tree
    /// `IAMResourceTree` walks, as membership declarations.
    private static func parentTypes(for entity: CedarEntityType) -> [CedarEntityType] {
        switch entity {
        case .organization: return []
        case .folder: return [.organization, .folder]
        case .project: return [.organization, .folder]
        case .vm, .sandbox, .image, .volume, .volumeSnapshot, .sandboxSnapshot, .floatingIP, .serviceAccount:
            return [.project]
        case .network:
            // Project-scoped normally; a site-scoped network climbs to the
            // org or folder owning the site's capacity (`IAMResourceTree`).
            return [.project, .organization, .folder]
        case .site, .agent: return [.organization, .folder]
        case .user, .group, .workload: return []
        }
    }
}
