import CedarPolicy
import Foundation
import Vapor

// IAM roles/policies authoring, phase 2 (issue #605): reading a role's Cedar
// text back off the *parsed* policy.
//
// Role text arrives two ways — generated by the server from a picked action
// list, or written by hand in advanced mode — and both end up as a row whose
// `actions` column downstream code trusts. Deriving that column (and enforcing
// the shape rules) from Cedar's own EST rather than from the text means a role
// cannot say one thing to the evaluator and another to the catalog, the
// role-editor UI, or `WhoCanService`. Reformatting, comments, and whitespace
// are the parser's problem, not ours.

/// What a role's Cedar text turns out to say.
struct CedarRoleInspection: Equatable, Sendable {
    /// The action ids named by the permit's action scope, sorted and
    /// deduplicated — the `actions` column, derived rather than declared.
    let actions: [String]
}

/// Why a piece of role text is not usable as a role.
///
/// Every case is a `400`: role text is request input, and a role that cannot
/// be compiled is malformed rather than forbidden.
enum CedarRoleTextError: Error, AbortError, Equatable {
    case unparseable(String)
    case notAPermit(String)
    case boundPrincipalScope
    case unenumerableActionScope
    case noActions
    case unknownAction(String)
    case foreignGrantsFields([String])
    case grantsShapeMismatch
    case rejectedByCedar(String)

    var status: HTTPResponseStatus { .badRequest }

    var reason: String {
        switch self {
        case .unparseable(let detail):
            return "The role's Cedar text is not a single parseable policy: \(detail)"
        case .notAPermit(let effect):
            return
                "A role is a permit; effect '\(effect)' is not allowed. Ceilings that subtract are guardrails (/api/iam/guardrails)."
        case .boundPrincipalScope:
            return
                "A role's principal scope must be the unconstrained `principal` — who holds the role is decided by its bindings, not by its text."
        case .unenumerableActionScope:
            return
                "A role's action scope must be an explicit list (`action in [Action::\"vm:read\", …]`) so the actions it grants can be enumerated."
        case .noActions:
            return "A role must grant at least one action."
        case .unknownAction(let action):
            return "Unknown action '\(action)'. Use an action from the catalog (GET /api/iam/actions)."
        case .foreignGrantsFields(let fields):
            return
                "The role's text reads another role's grants (\(fields.joined(separator: ", "))). A role may only be conditioned on its own bindings."
        case .grantsShapeMismatch:
            return
                "A role's permit must be gated by its own grants: one `when` clause has to be exactly `principal in context.grants[\"<id>Users\"] || principal in context.grants[\"<id>Groups\"]`, written that way. Naming those fields inside a larger condition is not enough — a disjunction can widen the gate back to everyone. Add further `when`/`unless` clauses for extra conditions; they narrow, so they are always safe."
        case .rejectedByCedar(let detail):
            return "Cedar rejected the role's policy: \(detail)"
        }
    }
}

/// Parses role text and reads its shape off Cedar's EST.
enum CedarPolicyInspector {

    /// Parse `cedarText` as the permit for role `roleID`, enforce the role
    /// shape, and return what it grants.
    ///
    /// The shape rules are exactly the ones that keep a role a role:
    ///
    /// - **permit-only** — a `forbid` in the role store would be a ceiling
    ///   nobody could see from the guardrail API.
    /// - **unconstrained principal scope** — bindings decide who holds a role.
    /// - **enumerable action scope** — the `actions` column, and therefore the
    ///   catalog, who-can, and the editor, are derived from it.
    /// - **gated by its own grants** — one `when` clause must be exactly the
    ///   canonical disjunction over this role's grants fields, and no other
    ///   role's fields may appear anywhere.
    ///
    /// Everything else an author might add — `resource is VM`,
    /// `resource.environment == "staging"`, an MFA condition — is left alone,
    /// because Cedar conjoins condition clauses and so extra ones can only
    /// narrow what the gate already bounds.
    static func inspect(cedarText: String, roleID: UUID) throws -> CedarRoleInspection {
        let est = try parse(cedarText, roleID: roleID)

        let effect = est["effect"] as? String ?? "unknown"
        guard effect == "permit" else { throw CedarRoleTextError.notAPermit(effect) }

        guard let principal = est["principal"] as? [String: Any],
            principal["op"] as? String == "All"
        else { throw CedarRoleTextError.boundPrincipalScope }

        let actions = try actionScope(est)
        guard !actions.isEmpty else { throw CedarRoleTextError.noActions }
        for action in actions where !IAMRoleRegistry.allActions.contains(action) {
            throw CedarRoleTextError.unknownAction(action)
        }

        try checkGrantsGate(est, roleID: roleID)

        return CedarRoleInspection(actions: actions)
    }

    // MARK: - Parsing

    /// The policy's EST (Cedar's JSON policy format), as plain dictionaries.
    ///
    /// Kept untyped on purpose: the EST is a wide, versioned format, and a
    /// `Decodable` model of it would have to be extended in lockstep with
    /// Cedar to keep *parsing* — while everything below only asks a handful of
    /// questions of it. An unrecognized shape falls through to a shape
    /// rejection, which is the right answer for role text anyway.
    private static func parse(_ cedarText: String, roleID: UUID) throws -> [String: Any] {
        let policy: CedarPolicy.Policy
        do {
            // Text holding more than one policy fails here — `Policy` parses
            // exactly one, which is the "a role is a permit" rule's first leg.
            policy = try CedarPolicy.Policy(cedarText, id: RoleDescriptor.policyID(roleID))
        } catch {
            throw CedarRoleTextError.unparseable("\(error)")
        }
        do {
            let json = try policy.toJSON()
            guard let est = try JSONSerialization.jsonObject(with: Data(json.utf8)) as? [String: Any] else {
                throw CedarRoleTextError.unparseable("the policy did not render as a JSON object")
            }
            return est
        } catch let error as CedarRoleTextError {
            throw error
        } catch {
            throw CedarRoleTextError.unparseable("\(error)")
        }
    }

    // MARK: - Action scope

    /// The action ids the scope names, sorted and deduplicated.
    ///
    /// `action in [ … ]` is the canonical form and `action == Action::"x"` the
    /// degenerate one-action case; both are accepted. A one-element `in` list
    /// arrives here as the *singular* `entity` form, because Cedar collapses
    /// `action in [X]` and `action in X` to the same AST — which also means an
    /// action *group* reference (`action in Action::"svc:vm"`) is
    /// indistinguishable from a one-action list by shape. Nothing is lost:
    /// group names are not registry actions, so the caller's membership check
    /// rejects them by name, with a message that says which name.
    ///
    /// Only an unscoped `action` is refused here — it enumerates nothing, and
    /// a role whose action list silently grew with the next release is exactly
    /// what the curated registry exists to prevent.
    private static func actionScope(_ est: [String: Any]) throws -> [String] {
        guard let scope = est["action"] as? [String: Any], let op = scope["op"] as? String else {
            throw CedarRoleTextError.unenumerableActionScope
        }
        guard op == "==" || op == "in" else { throw CedarRoleTextError.unenumerableActionScope }

        if let entity = scope["entity"] as? [String: Any] {
            guard let id = actionID(entity) else { throw CedarRoleTextError.unenumerableActionScope }
            return [id]
        }
        guard let entities = scope["entities"] as? [[String: Any]] else {
            throw CedarRoleTextError.unenumerableActionScope
        }
        var ids: Set<String> = []
        for entity in entities {
            guard let id = actionID(entity) else { throw CedarRoleTextError.unenumerableActionScope }
            ids.insert(id)
        }
        return ids.sorted()
    }

    /// The id of an `Action::"…"` reference; nil for a reference to anything
    /// else, which cannot be an action.
    private static func actionID(_ entity: [String: Any]) -> String? {
        guard entity["type"] as? String == "Action" else { return nil }
        return entity["id"] as? String
    }

    // MARK: - Grants fields

    /// Require the permit to be *gated* by this role's grants, and to read no
    /// other role's.
    ///
    /// Two separate questions, and the difference between them is a security
    /// boundary:
    ///
    /// - **Which grants does it read?** Answered over attribute references
    ///   anywhere in the policy, since a reference to another role's fields is
    ///   wrong wherever it appears.
    /// - **Is it gated by them?** Answered structurally: one of the permit's
    ///   `when` clauses must be *exactly* the canonical disjunction. Merely
    ///   mentioning the fields is not being gated by them — a permit can name
    ///   both and neutralize them in the same breath:
    ///
    ///   ```
    ///   when { principal in context.grants["…Users"]
    ///       || principal in context.grants["…Groups"]
    ///       || principal == principal }
    ///   ```
    ///
    ///   which references exactly the right fields and grants to everyone on
    ///   everything, with no binding behind it. `||` can always widen a
    ///   disjunct back to true, and no amount of looking at *which* names
    ///   appear can see that; only the shape of the clause can.
    ///
    /// Requiring exact equality on one clause is safe to build on because
    /// Cedar conjoins condition clauses: with the canonical disjunction as one
    /// clause, the permit cannot match a principal outside the role's grants,
    /// and every further `when`/`unless` can only narrow it. That is what lets
    /// arbitrary extra conditions stay legal without weakening anything.
    ///
    /// The comparison is on the parsed EST, not the text, so formatting,
    /// comments, and whitespace are free — but the disjunction itself must be
    /// written the way `RoleDescriptor.canonicalPermitText` writes it. That is
    /// a real constraint on hand-written text, and the error message spells
    /// out the required clause rather than leaving the author to guess.
    private static func checkGrantsGate(_ est: [String: Any], roleID: UUID) throws {
        var attributes: Set<String> = []
        collectAttributeNames(est, into: &attributes)

        let own: Set<String> = [
            RoleDescriptor.grantsUsersField(roleID),
            RoleDescriptor.grantsGroupsField(roleID),
        ]
        let foreign = attributes.filter(isGrantsFieldName).subtracting(own)
        guard foreign.isEmpty else {
            throw CedarRoleTextError.foreignGrantsFields(foreign.sorted())
        }

        let canonical = try canonicalGrantsCondition(roleID: roleID)
        let clauses = est["conditions"] as? [[String: Any]] ?? []
        let gated = clauses.contains { clause in
            guard clause["kind"] as? String == "when", let body = clause["body"] else { return false }
            return stableJSON(body) == canonical
        }
        guard gated else { throw CedarRoleTextError.grantsShapeMismatch }
    }

    /// The canonical grants disjunction for a role, as a stable JSON rendering
    /// of its EST — read from the generated permit itself, so the accepted
    /// shape and the generated one cannot drift apart.
    ///
    /// The action list is irrelevant to the condition and is only here because
    /// a permit needs one to parse; nothing validates it against the registry
    /// at this point.
    private static func canonicalGrantsCondition(roleID: UUID) throws -> String {
        let text = RoleDescriptor.canonicalPermitText(id: roleID, actions: ["placeholder"])
        let est = try parse(text, roleID: roleID)
        guard let clauses = est["conditions"] as? [[String: Any]],
            let body = clauses.first(where: { $0["kind"] as? String == "when" })?["body"]
        else {
            throw CedarRoleTextError.unparseable("the canonical role permit has no `when` clause")
        }
        return stableJSON(body)
    }

    /// A comparable rendering of an EST fragment: sorted keys, so two
    /// structurally identical conditions compare equal regardless of the order
    /// the parser happened to emit their fields in.
    private static func stableJSON(_ value: Any) -> String {
        guard JSONSerialization.isValidJSONObject([value]),
            let data = try? JSONSerialization.data(withJSONObject: [value], options: [.sortedKeys])
        else {
            // Unrenderable means "not equal to the canonical clause", which is
            // the safe answer: it fails the gate check rather than passing it.
            return "<unrenderable>"
        }
        return String(decoding: data, as: UTF8.self)
    }

    /// Every attribute name the EST reads (`x.foo` and `x["foo"]` are the same
    /// node, so both are covered).
    private static func collectAttributeNames(_ value: Any, into names: inout Set<String>) {
        if let object = value as? [String: Any] {
            if let attribute = object["attr"] as? String { names.insert(attribute) }
            for nested in object.values {
                collectAttributeNames(nested, into: &names)
            }
        } else if let array = value as? [Any] {
            for element in array {
                collectAttributeNames(element, into: &names)
            }
        }
    }

    /// Whether a name is a grants field — `<role uuid>Users` / `<role
    /// uuid>Groups`, the naming `RoleDescriptor` generates.
    private static func isGrantsFieldName(_ name: String) -> Bool {
        for suffix in ["Users", "Groups"] where name.hasSuffix(suffix) {
            return UUID(uuidString: String(name.dropLast(suffix.count))) != nil
        }
        return false
    }
}
