import CedarPolicy
import Foundation
import Vapor

// IAM roles/policies authoring, phase 2 (issue #605): reading a role's Cedar
// text back off the *parsed* policy.
//
// Role text arrives two ways — generated by the server from a picked action
// list, or written by hand in advanced mode — and both end up as a row whose
// `actions` column downstream code trusts. Deriving that column (and enforcing
// the shape rules) from Cedar's own EST rather than from the text means a role
// cannot say one thing to the evaluator and another to the catalog, the
// role-editor UI, or `WhoCanService`. Reformatting, comments, and whitespace
// are the parser's problem, not ours.

/// What a role's Cedar text turns out to say.
struct CedarRoleInspection: Equatable, Sendable {
    /// The action ids named by the permit's action scope, sorted and
    /// deduplicated — the `actions` column, derived rather than declared.
    let actions: [String]
}

/// Why a piece of role text is not usable as a role.
///
/// Every case is a `400`: role text is request input, and a role that cannot
/// be compiled is malformed rather than forbidden.
enum CedarRoleTextError: Error, AbortError, Equatable {
    case unparseable(String)
    case notAPermit(String)
    case boundPrincipalScope
    case unenumerableActionScope
    case noActions
    case unknownAction(String)
    case foreignGrantsFields([String])
    case grantsShapeMismatch
    case rejectedByCedar(String)

    var status: HTTPResponseStatus { .badRequest }

    var reason: String {
        switch self {
        case .unparseable(let detail):
            return "The role's Cedar text is not a single parseable policy: \(detail)"
        case .notAPermit(let effect):
            return
                "A role is a permit; effect '\(effect)' is not allowed. Ceilings that subtract are guardrails (/api/iam/guardrails)."
        case .boundPrincipalScope:
            return
                "A role's principal scope must be the unconstrained `principal` — who holds the role is decided by its bindings, not by its text."
        case .unenumerableActionScope:
            return
                "A role's action scope must be an explicit list (`action in [Action::\"vm:read\", …]`) so the actions it grants can be enumerated."
        case .noActions:
            return "A role must grant at least one action."
        case .unknownAction(let action):
            return "Unknown action '\(action)'. Use an action from the catalog (GET /api/iam/actions)."
        case .foreignGrantsFields(let fields):
            return
                "The role's text reads another role's grants (\(fields.joined(separator: ", "))). A role may only be conditioned on its own bindings."
        case .grantsShapeMismatch:
            return
                "A role's permit must be conditioned on its own grants — `principal in context.grants[\"<id>Users\"] || principal in context.grants[\"<id>Groups\"]`. Without it the role would grant to everyone; extra `when` conditions on top are fine."
        case .rejectedByCedar(let detail):
            return "Cedar rejected the role's policy: \(detail)"
        }
    }
}

/// Parses role text and reads its shape off Cedar's EST.
enum CedarPolicyInspector {

    /// Parse `cedarText` as the permit for role `roleID`, enforce the role
    /// shape, and return what it grants.
    ///
    /// The shape rules are exactly the ones that keep a role a role:
    ///
    /// - **permit-only** — a `forbid` in the role store would be a ceiling
    ///   nobody could see from the guardrail API.
    /// - **unconstrained principal scope** — bindings decide who holds a role.
    /// - **enumerable action scope** — the `actions` column, and therefore the
    ///   catalog, who-can, and the editor, are derived from it.
    /// - **its own grants fields, both of them** — the permit must be gated on
    ///   this role's bindings and no other role's.
    ///
    /// Everything else an author might add — `resource is VM`,
    /// `resource.environment == "staging"`, an MFA condition — is left alone.
    static func inspect(cedarText: String, roleID: UUID) throws -> CedarRoleInspection {
        let est = try parse(cedarText, roleID: roleID)

        let effect = est["effect"] as? String ?? "unknown"
        guard effect == "permit" else { throw CedarRoleTextError.notAPermit(effect) }

        guard let principal = est["principal"] as? [String: Any],
            principal["op"] as? String == "All"
        else { throw CedarRoleTextError.boundPrincipalScope }

        let actions = try actionScope(est)
        guard !actions.isEmpty else { throw CedarRoleTextError.noActions }
        for action in actions where !IAMRoleRegistry.allActions.contains(action) {
            throw CedarRoleTextError.unknownAction(action)
        }

        try checkGrantsFields(est, roleID: roleID)

        return CedarRoleInspection(actions: actions)
    }

    // MARK: - Parsing

    /// The policy's EST (Cedar's JSON policy format), as plain dictionaries.
    ///
    /// Kept untyped on purpose: the EST is a wide, versioned format, and a
    /// `Decodable` model of it would have to be extended in lockstep with
    /// Cedar to keep *parsing* — while everything below only asks a handful of
    /// questions of it. An unrecognized shape falls through to a shape
    /// rejection, which is the right answer for role text anyway.
    private static func parse(_ cedarText: String, roleID: UUID) throws -> [String: Any] {
        let policy: CedarPolicy.Policy
        do {
            // Text holding more than one policy fails here — `Policy` parses
            // exactly one, which is the "a role is a permit" rule's first leg.
            policy = try CedarPolicy.Policy(cedarText, id: RoleDescriptor.policyID(roleID))
        } catch {
            throw CedarRoleTextError.unparseable("\(error)")
        }
        do {
            let json = try policy.toJSON()
            guard let est = try JSONSerialization.jsonObject(with: Data(json.utf8)) as? [String: Any] else {
                throw CedarRoleTextError.unparseable("the policy did not render as a JSON object")
            }
            return est
        } catch let error as CedarRoleTextError {
            throw error
        } catch {
            throw CedarRoleTextError.unparseable("\(error)")
        }
    }

    // MARK: - Action scope

    /// The action ids the scope names, sorted and deduplicated.
    ///
    /// `action in [ … ]` is the canonical form and `action == Action::"x"` the
    /// degenerate one-action case; both are accepted. A one-element `in` list
    /// arrives here as the *singular* `entity` form, because Cedar collapses
    /// `action in [X]` and `action in X` to the same AST — which also means an
    /// action *group* reference (`action in Action::"svc:vm"`) is
    /// indistinguishable from a one-action list by shape. Nothing is lost:
    /// group names are not registry actions, so the caller's membership check
    /// rejects them by name, with a message that says which name.
    ///
    /// Only an unscoped `action` is refused here — it enumerates nothing, and
    /// a role whose action list silently grew with the next release is exactly
    /// what the curated registry exists to prevent.
    private static func actionScope(_ est: [String: Any]) throws -> [String] {
        guard let scope = est["action"] as? [String: Any], let op = scope["op"] as? String else {
            throw CedarRoleTextError.unenumerableActionScope
        }
        guard op == "==" || op == "in" else { throw CedarRoleTextError.unenumerableActionScope }

        if let entity = scope["entity"] as? [String: Any] {
            guard let id = actionID(entity) else { throw CedarRoleTextError.unenumerableActionScope }
            return [id]
        }
        guard let entities = scope["entities"] as? [[String: Any]] else {
            throw CedarRoleTextError.unenumerableActionScope
        }
        var ids: Set<String> = []
        for entity in entities {
            guard let id = actionID(entity) else { throw CedarRoleTextError.unenumerableActionScope }
            ids.insert(id)
        }
        return ids.sorted()
    }

    /// The id of an `Action::"…"` reference; nil for a reference to anything
    /// else, which cannot be an action.
    private static func actionID(_ entity: [String: Any]) -> String? {
        guard entity["type"] as? String == "Action" else { return nil }
        return entity["id"] as? String
    }

    // MARK: - Grants fields

    /// Require the permit to read exactly this role's two grants fields.
    ///
    /// The check is on attribute *references* anywhere in the policy rather
    /// than on a particular condition shape, because there are many ways to
    /// spell the same disjunction and only one thing that matters: which
    /// role's bindings gate this permit.
    private static func checkGrantsFields(_ est: [String: Any], roleID: UUID) throws {
        var attributes: Set<String> = []
        collectAttributeNames(est, into: &attributes)

        let referenced = attributes.filter(isGrantsFieldName)
        let own: Set<String> = [
            RoleDescriptor.grantsUsersField(roleID),
            RoleDescriptor.grantsGroupsField(roleID),
        ]
        let foreign = referenced.subtracting(own)
        guard foreign.isEmpty else {
            throw CedarRoleTextError.foreignGrantsFields(foreign.sorted())
        }
        guard referenced == own else { throw CedarRoleTextError.grantsShapeMismatch }
    }

    /// Every attribute name the EST reads (`x.foo` and `x["foo"]` are the same
    /// node, so both are covered).
    private static func collectAttributeNames(_ value: Any, into names: inout Set<String>) {
        if let object = value as? [String: Any] {
            if let attribute = object["attr"] as? String { names.insert(attribute) }
            for nested in object.values {
                collectAttributeNames(nested, into: &names)
            }
        } else if let array = value as? [Any] {
            for element in array {
                collectAttributeNames(element, into: &names)
            }
        }
    }

    /// Whether a name is a grants field — `<role uuid>Users` / `<role
    /// uuid>Groups`, the naming `RoleDescriptor` generates.
    private static func isGrantsFieldName(_ name: String) -> Bool {
        for suffix in ["Users", "Groups"] where name.hasSuffix(suffix) {
            return UUID(uuidString: String(name.dropLast(suffix.count))) != nil
        }
        return false
    }
}
