//! Guest networking — the portable half (STR-101).
//!
//! The syscall side (matching the NIC by MAC, addresses, routes, MTU) is
//! Linux-only and lives in `src/linux/net.rs`. What lives here is the part
//! that is just text and rules: rendering the resolver files the init drops
//! into the container rootfs, and validating a hostname before it is handed to
//! `sethostname`. Keeping them here means they are unit-tested on any host,
//! like the config merge and the vsock protocol.

use crate::config::NetworkConfig;

/// Where the resolver config goes inside the container rootfs.
pub const RESOLV_CONF_PATH: &str = "/etc/resolv.conf";

/// Where the static host table goes inside the container rootfs.
pub const HOSTS_PATH: &str = "/etc/hosts";

/// Marker on the first line of every file this init writes, so anyone reading
/// one inside a sandbox knows it was generated and not shipped in the image.
const BANNER: &str = "# Generated by strato-sandbox-init";

/// Render `/etc/resolv.conf` for this NIC, or `None` when the network carries
/// neither resolvers nor search domains — in which case the image's own file
/// (if it has one) is left alone rather than replaced with an empty one.
///
/// Note that resolvers cap what they read: both glibc and musl honour at most
/// three `nameserver` lines. Everything the control plane sent is written
/// anyway — truncating here would hide a misconfiguration that is visible in
/// the file.
pub fn resolv_conf(config: &NetworkConfig) -> Option<String> {
    let nameservers: Vec<&str> = non_empty(&config.nameservers);
    let search: Vec<&str> = non_empty(&config.search_domains);
    if nameservers.is_empty() && search.is_empty() {
        return None;
    }

    let mut out = String::from(BANNER);
    out.push('\n');
    if !search.is_empty() {
        out.push_str("search ");
        out.push_str(&search.join(" "));
        out.push('\n');
    }
    for server in nameservers {
        out.push_str("nameserver ");
        out.push_str(server);
        out.push('\n');
    }
    Some(out)
}

/// Render `/etc/hosts`: the conventional loopback entries every workload
/// expects, plus this NIC's addresses mapped to the sandbox's hostname.
///
/// Always produced when the sandbox is networked, even with no hostname —
/// a scratch or distroless image may ship no `/etc/hosts` at all, and then
/// resolving `localhost` fails for want of a file rather than for want of a
/// network.
pub fn hosts_file(config: &NetworkConfig) -> String {
    let mut out = String::from(BANNER);
    out.push('\n');
    out.push_str("127.0.0.1\tlocalhost\n");
    out.push_str("::1\tlocalhost ip6-localhost ip6-loopback\n");

    if let Some(hostname) = config.hostname.as_deref().filter(|h| !h.is_empty()) {
        for address in [
            config.ipv4.as_ref().map(|a| a.address.as_str()),
            config.ipv6.as_ref().map(|a| a.address.as_str()),
        ]
        .into_iter()
        .flatten()
        .filter(|a| !a.is_empty())
        {
            out.push_str(address);
            out.push('\t');
            out.push_str(hostname);
            out.push('\n');
        }
    }
    out
}

/// Check a hostname is something `sethostname` will accept and a resolver will
/// not choke on: 1...63 bytes, no NUL, no whitespace. Deliberately not a full
/// DNS-label check — the host derives these names, and a guest that rejects a
/// name the host considers valid would fail a boot over cosmetics.
pub fn validate_hostname(hostname: &str) -> Result<(), String> {
    if hostname.is_empty() || hostname.len() > 63 {
        return Err("hostname must contain 1...63 bytes".to_string());
    }
    if hostname
        .as_bytes()
        .iter()
        .any(|b| *b == 0 || b.is_ascii_whitespace())
    {
        return Err("hostname must contain no NUL or whitespace bytes".to_string());
    }
    Ok(())
}

/// Trim each entry and drop the ones that were blank — the control plane's
/// optional string fields arrive as `""` often enough to be worth filtering in
/// one place.
fn non_empty(values: &[String]) -> Vec<&str> {
    values
        .iter()
        .map(|v| v.trim())
        .filter(|v| !v.is_empty())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::AddressConfig;

    fn dual_stack() -> NetworkConfig {
        NetworkConfig {
            mac_address: Some("06:00:ac:10:00:05".into()),
            ipv4: Some(AddressConfig {
                address: "172.16.0.5".into(),
                prefix_length: 24,
                gateway: Some("172.16.0.1".into()),
            }),
            ipv6: Some(AddressConfig {
                address: "fd12:3456:789a::5".into(),
                prefix_length: 64,
                gateway: Some("fd12:3456:789a::1".into()),
            }),
            mtu: Some(1442),
            nameservers: vec!["172.16.0.2".into(), "1.1.1.1".into()],
            search_domains: vec!["proj.strato.internal".into()],
            hostname: Some("strato-abc123".into()),
        }
    }

    #[test]
    fn resolv_conf_lists_search_then_nameservers() {
        let rendered = resolv_conf(&dual_stack()).expect("resolvers");
        assert_eq!(
            rendered,
            "# Generated by strato-sandbox-init\n\
             search proj.strato.internal\n\
             nameserver 172.16.0.2\n\
             nameserver 1.1.1.1\n"
        );
    }

    #[test]
    fn resolv_conf_is_omitted_when_there_is_nothing_to_say() {
        let mut config = dual_stack();
        config.nameservers.clear();
        config.search_domains.clear();
        assert!(resolv_conf(&config).is_none());

        // Blank strings are nothing to say either: writing `nameserver ` would
        // break a resolver that the absent file would not have.
        config.nameservers = vec!["".into(), "  ".into()];
        assert!(resolv_conf(&config).is_none());
    }

    #[test]
    fn hosts_maps_both_families_to_the_hostname() {
        assert_eq!(
            hosts_file(&dual_stack()),
            "# Generated by strato-sandbox-init\n\
             127.0.0.1\tlocalhost\n\
             ::1\tlocalhost ip6-localhost ip6-loopback\n\
             172.16.0.5\tstrato-abc123\n\
             fd12:3456:789a::5\tstrato-abc123\n"
        );
    }

    #[test]
    fn hosts_still_covers_localhost_without_a_hostname() {
        let config = NetworkConfig {
            hostname: None,
            ..dual_stack()
        };
        let rendered = hosts_file(&config);
        assert!(rendered.contains("127.0.0.1\tlocalhost\n"));
        assert!(
            !rendered.contains("172.16.0.5"),
            "no hostname means nothing to map an address to"
        );
    }

    #[test]
    fn hostnames_are_checked_before_sethostname_sees_them() {
        assert_eq!(validate_hostname("strato-abc123"), Ok(()));
        assert!(validate_hostname("").is_err());
        assert!(validate_hostname(&"a".repeat(64)).is_err());
        assert!(validate_hostname("has space").is_err());
        assert!(validate_hostname("has\0nul").is_err());
    }
}
