apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "strato-control-plane.fullname" . }}
  labels:
    {{- include "strato-control-plane.labels" . | nindent 4 }}
data:
  spicedb-schema.zed: |
    definition user {
    }

    definition organization {
        relation admin: user
        relation member: user

        permission create_vm = admin
        permission manage_members = admin
        permission view = member + admin
    }

    definition vm {
        relation owner: user
        relation organization: organization

        permission start = owner + organization->admin
        permission stop = owner + organization->admin
        permission restart = owner + organization->admin
        permission delete = owner + organization->admin
        permission update = owner + organization->admin
        permission read = owner + organization->member
    }