{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "strato-control-plane.fullname" . }}
  labels:
    {{- include "strato-control-plane.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "strato-control-plane.selectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if and .Values.spicedb.enabled .Values.spicedb.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "strato-control-plane.fullname" . }}-spicedb
  labels:
    {{- include "strato-control-plane.spicedb.labels" . | nindent 4 }}
spec:
  {{- if .Values.spicedb.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.spicedb.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.spicedb.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.spicedb.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "strato-control-plane.spicedb.selectorLabels" . | nindent 6 }}
{{- end }}