{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strato-control-plane.fullname" . }}-external-db
  labels:
    {{- include "strato-control-plane.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
---
{{- if .Values.spicedb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strato-control-plane.fullname" . }}-spicedb
  labels:
    {{- include "strato-control-plane.spicedb.labels" . | nindent 4 }}
type: Opaque
data:
  preshared-key: {{ .Values.spicedb.presharedKey | b64enc | quote }}
{{- end }}