{{- if and (not .Values.postgresql.enabled) .Values.externalDatabase.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strato-control-plane.fullname" . }}-external-db
  labels:
    {{- include "strato-control-plane.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
---
{{- if .Values.spicedb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strato-control-plane.fullname" . }}-spicedb
  labels:
    {{- include "strato-control-plane.spicedb.labels" . | nindent 4 }}
type: Opaque
data:
  preshared-key: {{ .Values.spicedb.presharedKey | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  datastore-conn-uri: {{ printf "postgres://%s:%s@%s:%v/%s?sslmode=disable" .Values.strato.database.username .Values.postgresql.auth.password (include "strato-control-plane.databaseHost" .) .Values.strato.database.port .Values.strato.database.name | b64enc | quote }}
  {{- else if .Values.externalDatabase.password }}
  datastore-conn-uri: {{ printf "postgres://%s:%s@%s:%v/%s?sslmode=disable" .Values.strato.database.username .Values.externalDatabase.password (include "strato-control-plane.databaseHost" .) .Values.strato.database.port .Values.strato.database.name | b64enc | quote }}
  {{- end }}
{{- end }}