{{- if and .Values.spicedb.enabled .Values.spicedb.schema.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "strato-control-plane.spicedb.fullname" . }}-schema
  labels:
    {{- include "strato-control-plane.spicedb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "strato-control-plane.spicedb.baseLabels" . | nindent 8 }}
        app.kubernetes.io/component: spicedb-schema
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-spicedb
          image: {{ default "busybox:1.36.1" .Values.initContainers.waitForSpiceDB.image | quote }}
          command:
            - sh
            - -c
            - |
              until nc -w 1 -z {{ include "strato-control-plane.spicedb.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local {{ .Values.spicedb.service.grpcPort }}; do echo waiting for SpiceDB; sleep 2; done
      containers:
        - name: schema-loader
          image: authzed/zed:latest
          command:
            - zed
            - schema
            - write
            - /schema/spicedb-schema.zed
            - --endpoint
            - {{ include "strato-control-plane.spicedb.fullname" . }}:50051
            - --token
            - $(SPICEDB_TOKEN)
            - --insecure
          env:
            - name: SPICEDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "strato-control-plane.spicedb.fullname" . }}-config
                  key: preshared-key
          volumeMounts:
            - name: schema
              mountPath: /schema
      volumes:
        - name: schema
          configMap:
            name: {{ include "strato-control-plane.fullname" . }}
{{- end }}
