{{- if .Values.spicedb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "strato-control-plane.spicedb.fullname" . }}
  labels:
    {{- include "strato-control-plane.spicedb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "strato-control-plane.spicedb.fullname" . }}
  replicas: {{ .Values.spicedb.replicaCount }}
  selector:
    matchLabels:
      {{- include "strato-control-plane.spicedb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "strato-control-plane.spicedb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-db
          image: {{ default "busybox:1.36.1" .Values.initContainers.waitForDB.image | quote }}
          command:
            - sh
            - -c
            - |
              until nc -w 1 -z {{ include "strato-control-plane.databaseHost" . }}.{{ .Release.Namespace }}.svc.cluster.local {{ .Values.strato.database.port }}; do echo waiting for database; sleep 2; done
        - name: spicedb-migrate
          image: "{{ .Values.spicedb.image.repository }}:{{ .Values.spicedb.image.tag }}"
          imagePullPolicy: {{ .Values.spicedb.image.pullPolicy }}
          command: ["spicedb", "migrate", "head"]
          env:
            - name: SPICEDB_DATASTORE_ENGINE
              value: postgres
            - name: SPICEDB_DATASTORE_CONN_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "strato-control-plane.spicedb.fullname" . }}-config
                  key: datastore-conn-uri
      containers:
        - name: spicedb
          image: "{{ .Values.spicedb.image.repository }}:{{ .Values.spicedb.image.tag }}"
          imagePullPolicy: {{ .Values.spicedb.image.pullPolicy }}
          command: 
            - "spicedb"
            - "serve"
            - "--grpc-preshared-key"
            - "$(SPICEDB_GRPC_PRESHARED_KEY)"
            - "--http-enabled"
            - "--http-addr"
            - ":8080"
            - "--grpc-addr"
            - ":50051"
          ports:
            - name: grpc
              containerPort: {{ .Values.spicedb.service.grpcPort }}
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.spicedb.service.metricsPort }}
              protocol: TCP
          env:
            - name: SPICEDB_GRPC_PRESHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "strato-control-plane.spicedb.fullname" . }}-config
                  key: preshared-key
            - name: SPICEDB_DATASTORE_ENGINE
              value: postgres
            - name: SPICEDB_DATASTORE_CONN_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "strato-control-plane.spicedb.fullname" . }}-config
                  key: datastore-conn-uri
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          {{- if .Values.spicedb.resources }}
          resources:
            {{- toYaml .Values.spicedb.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.spicedb.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.spicedb.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.spicedb.persistence.storageClass }}
        storageClassName: {{ .Values.spicedb.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.spicedb.persistence.size }}
  {{- end }}
{{- end }}
