{{- if .Values.stepCA.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strato-control-plane.fullname" . }}-step-ca
  labels:
    {{- include "strato-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: step-ca
type: Opaque
data:
  password.txt: {{ .Values.stepCA.init.password | b64enc }}
  provisioner-password.txt: {{ .Values.stepCA.init.provisionerPassword | b64enc }}
{{- end }}