#!/usr/bin/env bash
#
# First-run setup for the Strato single-host deployment.
# Generates a .env file with strong random secrets. Idempotent: if .env
# already exists it is left untouched (regenerating the database password
# would strand the already-initialized PostgreSQL volume).
#
# Usage:
#   ./setup.sh                            # localhost, port 80
#   ./setup.sh --hostname strato.example.com
#   ./setup.sh --hostname localhost --port 8888
set -euo pipefail

cd "$(dirname "$0")"

HOSTNAME_ARG="localhost"
PORT_ARG="80"
# Envoy mTLS listener + SPIRE node API ports agents connect to. Kept fixed to
# match the published ports and the control plane's :8085 derivation; override
# in .env only if you also change docker-compose.yml.
AGENT_MTLS_PORT="8443"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --hostname)
      HOSTNAME_ARG="$2"
      shift 2
      ;;
    --port)
      PORT_ARG="$2"
      shift 2
      ;;
    -h|--help)
      sed -n '3,11p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Unknown argument: $1 (see --help)" >&2
      exit 1
      ;;
  esac
done

if [[ -f .env ]]; then
  echo ".env already exists — leaving it untouched."
  echo "To reconfigure non-secret settings, edit .env directly."
  # Upgrade guard: agents now authenticate over Envoy mTLS on :${AGENT_MTLS_PORT},
  # so EXTERNAL_HOSTNAME must carry that port. A .env generated before this
  # (EXTERNAL_HOSTNAME = the browser endpoint) makes the control plane emit
  # agent bootstrap URLs that dial the wrong port.
  if grep -q '^EXTERNAL_HOSTNAME=' .env && ! grep -qE "^EXTERNAL_HOSTNAME=.+:${AGENT_MTLS_PORT}\$" .env; then
    echo
    echo "WARNING: EXTERNAL_HOSTNAME in .env is not '<hostname>:${AGENT_MTLS_PORT}'."
    echo "Agents authenticate over Envoy mTLS now — set it to your hostname with"
    echo ":${AGENT_MTLS_PORT} appended, or agent bootstrap commands will dial the wrong port."
  fi
  # An existing .env generated with HTTP_PORT == the mTLS port can't stand up:
  # nginx and Envoy would both try to publish that host port.
  if grep -qE "^HTTP_PORT=${AGENT_MTLS_PORT}\$" .env; then
    echo
    echo "WARNING: HTTP_PORT in .env is ${AGENT_MTLS_PORT}, which collides with the"
    echo "agent mTLS port. Change HTTP_PORT — nginx and Envoy cannot share it."
  fi
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "Error: openssl is required to generate secrets." >&2
  exit 1
fi

# The Envoy agent-mTLS listener claims ${AGENT_MTLS_PORT}; the browser proxy
# cannot also bind it. Reject the collision rather than generate an unstartable
# stack (both services would try to publish the same host port).
if [[ "$PORT_ARG" == "$AGENT_MTLS_PORT" ]]; then
  echo "Error: --port $PORT_ARG collides with the agent mTLS port (${AGENT_MTLS_PORT})." >&2
  echo "Pick a different HTTP port (the mTLS listener needs ${AGENT_MTLS_PORT})." >&2
  exit 1
fi

# WebAuthn requires a secure context: plain HTTP is only allowed for
# localhost. Any real hostname must be served over HTTPS (terminate TLS in
# front of the proxy service, or extend nginx.conf with a TLS listener).
if [[ "$HOSTNAME_ARG" == "localhost" || "$HOSTNAME_ARG" == "127.0.0.1" ]]; then
  SCHEME="http"
else
  SCHEME="https"
fi

if [[ ( "$SCHEME" == "http" && "$PORT_ARG" != "80" ) || ( "$SCHEME" == "https" && "$PORT_ARG" != "443" ) ]]; then
  ORIGIN="${SCHEME}://${HOSTNAME_ARG}:${PORT_ARG}"
else
  ORIGIN="${SCHEME}://${HOSTNAME_ARG}"
fi

# Agents authenticate over mTLS to the Envoy listener, a TLS port separate from
# the browser proxy, so EXTERNAL_HOSTNAME points at <hostname>:<mTLS port>
# regardless of the HTTP port. The control plane always emits wss:// agent URLs
# when SPIRE is enabled, so this works for http:// (localhost) origins too.
EXTERNAL_HOSTNAME="${HOSTNAME_ARG}:${AGENT_MTLS_PORT}"

umask 077
cat > .env <<EOF
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Mode 0600 — this
# file holds the deployment's secrets. Do not commit it.

# --- Secrets (generated; do not change after first start: the database was
# --- initialized with this password) ---
POSTGRES_PASSWORD=$(openssl rand -hex 32)
VALKEY_PASSWORD=$(openssl rand -hex 32)
# Encrypts OIDC client secrets at rest in the database. If this key is lost,
# stored client secrets become unreadable (re-enter them in the UI to recover).
STRATO_SECRET_ENCRYPTION_KEY=$(openssl rand -hex 32)

# --- Hostname / WebAuthn ---
# The exact origin users visit in the browser. Passkey registration fails if
# this does not match, so change it (and re-register users) when the
# hostname changes. Non-localhost hostnames require HTTPS.
STRATO_HOSTNAME=${HOSTNAME_ARG}
# Host:port agents use to reach the control plane over mTLS (the Envoy
# listener); embedded in the bootstrap commands the UI generates. This is the
# agent-facing endpoint, not the browser proxy.
EXTERNAL_HOSTNAME=${EXTERNAL_HOSTNAME}
# Published proxy origin (the browser URL). Only used as the BASE_URL default
# below; agents fetch images through the mTLS listener, not this origin.
CONTROL_PLANE_URL=${ORIGIN}
# Public origin used to build OIDC redirect URIs (SSO login callback and
# post-logout redirect). Must be the exact browser origin; OIDC login fails
# loudly in production when this is unset.
BASE_URL=${ORIGIN}
WEBAUTHN_RELYING_PARTY_ID=${HOSTNAME_ARG}
WEBAUTHN_RELYING_PARTY_NAME=Strato
WEBAUTHN_RELYING_PARTY_ORIGIN=${ORIGIN}

# --- Service settings ---
HTTP_PORT=${PORT_ARG}
# Set to true once TLS is terminated in front of the proxy (required for any
# non-localhost origin). Makes the session cookie Secure and enables HSTS; leave
# false for plaintext http:// or the browser will drop the session cookie.
HTTP_TLS_ENABLED=$([[ "$SCHEME" == "https" ]] && echo true || echo false)
# Trusted proxy hops for reading the client IP in rate limiting. An HTTPS origin
# terminates TLS in front of nginx (terminator + nginx = 2 hops); plain http
# reaches nginx directly (1 hop). Setting this too low would bucket every client
# behind the outer proxy, so one user's failed logins could lock out the rest.
RATE_LIMIT_TRUSTED_PROXY_HOPS=$([[ "$SCHEME" == "https" ]] && echo 2 || echo 1)
LOG_LEVEL=info
# Image tag to deploy. `main` is rebuilt on every main-branch merge; pin an
# immutable build (e.g. STRATO_VERSION=main-abc123def456) or, once versioned
# releases exist, a release tag for reproducible deployments.
STRATO_VERSION=main
EOF

echo "Wrote .env (mode 0600) for ${ORIGIN}"
if [[ "$SCHEME" == "https" ]]; then
  echo
  echo "NOTE: ${HOSTNAME_ARG} is not localhost, so WebAuthn requires HTTPS."
  echo "Terminate TLS for ${ORIGIN} in front of the proxy service before"
  echo "registering users."
fi
echo
echo "Agents authenticate over mTLS: make sure ${HOSTNAME_ARG}:${AGENT_MTLS_PORT}"
echo "(Envoy) and ${HOSTNAME_ARG}:8085 (SPIRE) are reachable from your"
echo "hypervisor nodes. mTLS is end-to-end, so do NOT terminate TLS in front"
echo "of :${AGENT_MTLS_PORT}."
echo
echo "Next: docker compose up -d"
