#!/usr/bin/env bash
#
# First-run setup for the Strato single-host deployment.
# Generates a .env file with strong random secrets. Idempotent: if .env
# already exists it is left untouched (regenerating the database password
# would strand the already-initialized PostgreSQL volume).
#
# Usage:
#   ./setup.sh                            # localhost, port 80
#   ./setup.sh --hostname strato.example.com
#   ./setup.sh --hostname localhost --port 8888
set -euo pipefail

cd "$(dirname "$0")"

HOSTNAME_ARG="localhost"
PORT_ARG="80"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --hostname)
      HOSTNAME_ARG="$2"
      shift 2
      ;;
    --port)
      PORT_ARG="$2"
      shift 2
      ;;
    -h|--help)
      sed -n '3,11p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Unknown argument: $1 (see --help)" >&2
      exit 1
      ;;
  esac
done

if [[ -f .env ]]; then
  echo ".env already exists — leaving it untouched."
  echo "To reconfigure non-secret settings, edit .env directly."
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "Error: openssl is required to generate secrets." >&2
  exit 1
fi

# WebAuthn requires a secure context: plain HTTP is only allowed for
# localhost. Any real hostname must be served over HTTPS (terminate TLS in
# front of the proxy service, or extend nginx.conf with a TLS listener).
if [[ "$HOSTNAME_ARG" == "localhost" || "$HOSTNAME_ARG" == "127.0.0.1" ]]; then
  SCHEME="http"
else
  SCHEME="https"
fi

if [[ ( "$SCHEME" == "http" && "$PORT_ARG" != "80" ) || ( "$SCHEME" == "https" && "$PORT_ARG" != "443" ) ]]; then
  ORIGIN="${SCHEME}://${HOSTNAME_ARG}:${PORT_ARG}"
  EXTERNAL_HOSTNAME="${HOSTNAME_ARG}:${PORT_ARG}"
else
  ORIGIN="${SCHEME}://${HOSTNAME_ARG}"
  EXTERNAL_HOSTNAME="${HOSTNAME_ARG}"
fi

umask 077
cat > .env <<EOF
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Mode 0600 — this
# file holds the deployment's secrets. Do not commit it.

# --- Secrets (generated; do not change after first start: the database was
# --- initialized with this password) ---
POSTGRES_PASSWORD=$(openssl rand -hex 32)
SPICEDB_PRESHARED_KEY=$(openssl rand -hex 32)
VALKEY_PASSWORD=$(openssl rand -hex 32)

# --- Hostname / WebAuthn ---
# The exact origin users visit in the browser. Passkey registration fails if
# this does not match, so change it (and re-register users) when the
# hostname changes. Non-localhost hostnames require HTTPS.
STRATO_HOSTNAME=${HOSTNAME_ARG}
# Host (and port, when non-standard) agents use to reach the control plane;
# embedded in the join commands the UI generates.
EXTERNAL_HOSTNAME=${EXTERNAL_HOSTNAME}
WEBAUTHN_RELYING_PARTY_ID=${HOSTNAME_ARG}
WEBAUTHN_RELYING_PARTY_NAME=Strato
WEBAUTHN_RELYING_PARTY_ORIGIN=${ORIGIN}

# --- Service settings ---
HTTP_PORT=${PORT_ARG}
LOG_LEVEL=info
# Pin to a released version instead of latest for reproducible deployments,
# e.g. STRATO_VERSION=v0.5.0
STRATO_VERSION=latest
EOF

echo "Wrote .env (mode 0600) for ${ORIGIN}"
if [[ "$SCHEME" == "https" ]]; then
  echo
  echo "NOTE: ${HOSTNAME_ARG} is not localhost, so WebAuthn requires HTTPS."
  echo "Terminate TLS for ${ORIGIN} in front of the proxy service before"
  echo "registering users."
fi
echo
echo "Next: docker compose up -d"
