#!/usr/bin/env bash
# Verifies the repository-root Docker context does not include SwiftPM build
# output from any package. Source image builds run `COPY` from this context, so
# a nested host .build directory can otherwise replace artifacts generated by
# an earlier Dockerfile layer.
#
# The fixture is deliberately tiny but uses the repository's real
# .dockerignore. Exporting `COPY . /` through BuildKit tests Docker's ignore
# semantics directly instead of maintaining a second pattern matcher here.
#
#   bash deploy/compose/tests/docker-source-context-test.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
WORK_DIR="$(mktemp -d)"
IMAGE_REPOSITORY="strato-source-context-test-$$"

cleanup() {
  docker image rm \
    "$IMAGE_REPOSITORY:clean" \
    "$IMAGE_REPOSITORY:dirty" >/dev/null 2>&1 || true
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

CLEAN_CONTEXT_DIR="$WORK_DIR/clean-context"
DIRTY_CONTEXT_DIR="$WORK_DIR/dirty-context"
OUTPUT_DIR="$WORK_DIR/output"

mkdir -p "$CLEAN_CONTEXT_DIR"
cp "$REPO_ROOT/.dockerignore" "$CLEAN_CONTEXT_DIR/.dockerignore"
for package in control-plane shared agent; do
  mkdir -p "$CLEAN_CONTEXT_DIR/$package"
  printf 'must enter the Docker context\n' \
    > "$CLEAN_CONTEXT_DIR/$package/source.swift"
done
cp -R "$CLEAN_CONTEXT_DIR" "$DIRTY_CONTEXT_DIR"

for package in control-plane shared agent; do
  mkdir -p "$DIRTY_CONTEXT_DIR/$package/.build/nested"
  printf 'must not enter the Docker context\n' \
    > "$DIRTY_CONTEXT_DIR/$package/.build/nested/strato-context-sentinel"
done

build_context_image() {
  local context_dir="$1" iid_file="$2" image_tag="$3"
  printf 'FROM scratch\nCOPY . /\n' | docker buildx build \
    --file - \
    --iidfile "$iid_file" \
    --load \
    --tag "$image_tag" \
    "$context_dir"
}

build_context_image \
  "$CLEAN_CONTEXT_DIR" "$WORK_DIR/clean.iid" "$IMAGE_REPOSITORY:clean"
build_context_image \
  "$DIRTY_CONTEXT_DIR" "$WORK_DIR/dirty.iid" "$IMAGE_REPOSITORY:dirty"

if ! cmp -s "$WORK_DIR/clean.iid" "$WORK_DIR/dirty.iid"; then
  echo "FAIL: nested Swift build output changed the source image:" >&2
  printf '  clean: %s\n' "$(< "$WORK_DIR/clean.iid")" >&2
  printf '  dirty: %s\n' "$(< "$WORK_DIR/dirty.iid")" >&2
  exit 1
fi

printf 'FROM scratch\nCOPY . /\n' | docker buildx build \
  --file - \
  --output "type=local,dest=$OUTPUT_DIR" \
  "$DIRTY_CONTEXT_DIR"

if [[ ! -f "$OUTPUT_DIR/control-plane/source.swift" ]]; then
  echo "FAIL: ordinary source was missing from the Docker context" >&2
  exit 1
fi

mapfile -t nested_build_dirs < <(find "$OUTPUT_DIR" -type d -name .build -print)
if (( ${#nested_build_dirs[@]} > 0 )); then
  echo "FAIL: nested Swift build output entered the Docker context:" >&2
  printf '  %s\n' "${nested_build_dirs[@]}" >&2
  exit 1
fi

echo "Clean and dirty Docker source contexts produce the same image."
